namespace LittleTools.Assistant.Services;

internal static class TranslationImageCache
{
    internal static void Clear()
    {
        foreach (var root in new[] { AppPaths.DataDirectory, AppPaths.CacheDirectory })
        {
            ClearDirectory(Path.Combine(root, "translated-screenshots"));
        }
    }

    internal static void ClearDirectory(string directory)
    {
        if (!Directory.Exists(directory)) return;
        foreach (var file in Directory.EnumerateFiles(directory, "*.png", SearchOption.TopDirectoryOnly))
        {
            // Only files generated by this application, never user exports.
            if (!System.Text.RegularExpressions.Regex.IsMatch(Path.GetFileName(file), @"^[0-9a-f]{32}-\d{8}-\d{9}\.png$")) continue;
            try { File.Delete(file); }
            catch (IOException) { }
            catch (UnauthorizedAccessException) { }
        }
    }
}
